<script lang="ts">
  import CashFlowEditor from './lib/components/CashFlowEditor.svelte';
  import CalculationSettings from './lib/components/CalculationSettings.svelte';
  import BenchmarkHistorySection from './lib/components/BenchmarkHistorySection.svelte';
  import CurrentRateStrip from './lib/components/CurrentRateStrip.svelte';
  import FreshnessSummary from './lib/components/FreshnessSummary.svelte';
  import MethodologyDialog from './lib/components/MethodologyDialog.svelte';
  import ResultsSection from './lib/components/ResultsSection.svelte';
  import HistoricalSavingsSection, { type HistoricalSavingsDisplay } from './lib/components/HistoricalSavingsSection.svelte';
  import HistoricalSavingsResults from './lib/components/HistoricalSavingsResults.svelte';
  import FutureOutlookSection from './lib/components/FutureOutlookSection.svelte';
  import TaxRegimeControl from './lib/components/TaxRegimeControl.svelte';
  import { calculateBacktest } from './lib/services/backtest';
  import { createBenchmarkHistoryClient } from './lib/services/benchmark-history';
  import { loadMarketData } from './lib/services/market-data';
  import { createBacktestController } from './lib/state/backtest.svelte';
  import { onDestroy } from 'svelte';
  let setupTab = $state<'current' | 'historical'>('current');
  let historicalDisplay = $state<HistoricalSavingsDisplay>();
  let historicalScenario = $state<'monthly' | 'lumpSum'>('monthly');
  let historicalLoading = $state(false);
  let historicalSubmit = $state<(() => Promise<void>)>();
  let historicalEndDate = $state('');
  let historicalSetEndDate = $state<(value: string) => void>();
  let resultTab = $state<'outcome' | 'future'>('outcome');
  let openMethodology = $state<() => void>(() => {});
  const chooseSetupTab = (tab: 'current' | 'historical') => { setupTab = tab; };
  const focusCurrentAccountRate = () => {
    const target = document.getElementById('current-account-base-rate') as HTMLInputElement | null;
    if (!target) return;
    target.scrollIntoView({ behavior: 'smooth', block: 'center' });
    target.focus({ preventScroll: true });
  };
  const handleSetupTabKeydown = (event: KeyboardEvent) => {
    if (event.key !== 'ArrowLeft' && event.key !== 'ArrowRight' && event.key !== 'Home' && event.key !== 'End') return;
    event.preventDefault();
    const next = event.key === 'Home' || (event.key === 'ArrowLeft' && setupTab === 'historical') || (event.key === 'End' && setupTab === 'current') ? 'current' : 'historical';
    chooseSetupTab(next);
    document.getElementById(`${next}-backtest-tab`)?.focus();
  };
  const chooseResultTab = (tab: 'outcome' | 'future') => { resultTab = tab; };
  const handleResultTabKeydown = (event: KeyboardEvent) => {
    if (event.key !== 'ArrowLeft' && event.key !== 'ArrowRight' && event.key !== 'Home' && event.key !== 'End') return;
    event.preventDefault();
    const next = event.key === 'Home' || (event.key === 'ArrowLeft' && resultTab === 'future') || (event.key === 'End' && resultTab === 'outcome') ? 'outcome' : 'future';
    chooseResultTab(next);
    document.getElementById(`${next}-result-tab`)?.focus();
  };
  const benchmarkClient = createBenchmarkHistoryClient();
  const controller = createBacktestController({ storage: localStorage, today: () => new Date().toISOString().slice(0, 10), loadMarketData, calculate: calculateBacktest, prepareBenchmark: (request) => benchmarkClient.prepare(request) });
  void controller.loadBenchmark();
  if (controller.valid) void controller.calculate();
  onDestroy(() => benchmarkClient.dispose());
</script>
<svelte:head><script async defer src="https://buttons.github.io/buttons.js"></script></svelte:head>
<main class="app-shell max-w-375 pt-5 pb-10 mx-auto my-0 px-[clamp(20px,_2.2vw,_34px)] [@media(width<=600px)]:pt-3.5 [@media(width<=600px)]:pb-8 [@media(width<=600px)]:px-3">
  <header class="app-header mb-4 [@media(width<=760px)]:mb-2 [border-bottom-width:0px] [border-bottom-style:none] [border-bottom-color:currentcolor] pb-0 grid grid-cols-[auto_1fr_auto] items-center gap-4.5 [@media(width<=760px)]:pb-2 [@media(width<=760px)]:grid-cols-[1fr] [@media(width<=760px)]:gap-1.5">
    <div class="brand-lockup flex items-center gap-2.5"><span class="brand-mark grid w-8.5 h-7 place-items-center [border-bottom-width:2px] [border-bottom-style:solid] [border-bottom-color:var(--v2-green-dark)] text-accent-dark text-[1.5rem] font-[800] leading-[1]" aria-hidden="true">↗</span><div><p class="brand-kicker mt-0 mb-0.5 [color:var(--muted-ink)] text-[0.64rem] font-[750] tracking-[0.12em] uppercase hidden mx-0 [@media(width<=480px)]:text-[0.58rem]">Local analysis workspace</p><h1>CSH2 backtester</h1></div></div>
    <div class="header-utility [grid-column:2] grid min-w-0 gap-1 [@media(width<=760px)]:[grid-column:1]"><div class="header-context flex items-center justify-start [grid-column:2] gap-[9px] [@media(width<=760px)]:flex-col [@media(width<=760px)]:items-start [@media(width<=760px)]:gap-0 [@media(width<=760px)]:[grid-column:1]"><span class="privacy-note mt-2.5 mb-0 text-[#516158] text-[0.875rem] font-[650] leading-[1.5] mx-0">Your data stays in this browser</span><span class="header-dot text-accent-dark [@media(width<=760px)]:hidden" aria-hidden="true">•</span><span class="privacy-note mt-2.5 mb-0 text-[#516158] text-[0.875rem] font-[650] leading-[1.5] mx-0">Calculations run locally</span></div>{#if controller.view}<FreshnessSummary view={controller.view} />{/if}</div>
    <details class="header-details [grid-column:3] text-muted text-[0.75rem] m-0 [@media(width<=760px)]:[grid-column:1] [@media(width<=760px)]:ml-0"><summary>Data and model notes</summary><div><p class="header-assumption max-w-none mt-[5px] mb-0 text-muted text-[0.74rem] leading-[1.45] not-italic mx-0">By default, the backtest uses FIFO lots and assumes 10% CGT on positive realised gains from 2026 onward. For purchases before 2026, the tax basis is the higher of the original price and the 31 December 2025 CSH2 close.</p><p class="refresh-note mt-[5px] mb-0 text-muted text-[0.74rem] not-italic leading-[1.45] max-w-none mx-0">Market data refreshes automatically: CSH2 after midnight Tuesday–Saturday, €STR at 09:15 Monday–Friday, and Belgian CPI at 10:30 each Monday (Brussels time).</p></div></details>
  </header>
  <CurrentRateStrip {controller} onEditRate={focusCurrentAccountRate} onOpenMethodology={() => openMethodology()} />
  <TaxRegimeControl {controller} />
  <section class="secondary-analysis mt-3.5 [border-top-width:0px] [border-top-style:none] [border-top-color:currentcolor] pt-0 mb-4 mx-0" aria-label="Supporting analysis"><details class="analysis-disclosure bg-surface border border-solid border-line rounded-[5px]"><summary><span id="benchmark-context-heading">02 · Benchmark context</span><span class="disclosure-hint ml-auto text-muted text-[0.72rem] font-medium [@media(width<=600px)]:hidden">Historical benchmark returns</span></summary><div class="analysis-disclosure-content [border-top-width:1px] [border-top-style:solid] [border-top-color:var(--v2-border)] p-3.5 [@media(width<=600px)]:p-2.5"><BenchmarkHistorySection {controller} /></div></details></section>
  <div class="primary-workspace grid grid-cols-[minmax(290px,_0.43fr)_minmax(0px,_1fr)] [align-items:start] gap-4">
    <section class="configuration-column min-w-0 bg-surface pt-4 pb-4.5 px-[17px] border border-solid border-line rounded-[5px] [@media(width<=960px)]:pb-4 [@media(width<=960px)]:px-4" aria-labelledby="backtest-setup-heading">
      <div class="section-title config-title flex [align-items:end] justify-between pb-[11px] min-h-0 pt-0 mb-3 [border-bottom-width:1px] [border-bottom-style:solid] [border-bottom-color:var(--v2-border)] px-0 gap-5 [@media(width<=760px)]:items-start [@media(width<=760px)]:flex-col [@media(width<=760px)]:gap-3"><div><p class="eyebrow mb-1.5 text-muted text-[0.65rem] font-bold tracking-[0.09em] uppercase">03 · Configuration</p><h2 id="backtest-setup-heading">Set up your comparison</h2></div></div>
      <section class="input-section-container mb-0">
        <div class="setup-tabs flex w-full overflow-x-auto mb-4 bg-white border border-solid border-[#cbd7d0] rounded-[7px]" role="tablist" aria-label="Backtest type"><button id="current-backtest-tab" type="button" role="tab" tabindex={setupTab === 'current' ? 0 : -1} aria-selected={setupTab === 'current'} aria-controls="current-backtest-panel" onclick={() => chooseSetupTab('current')} onkeydown={handleSetupTabKeydown}>Current account backtest</button><button id="historical-backtest-tab" type="button" role="tab" tabindex={setupTab === 'historical' ? 0 : -1} aria-selected={setupTab === 'historical'} aria-controls="historical-backtest-panel" onclick={() => chooseSetupTab('historical')} onkeydown={handleSetupTabKeydown}>Historical savings rates</button></div>
      {#if setupTab === 'current'}<div id="current-backtest-panel" role="tabpanel" aria-labelledby="current-backtest-tab" class="panel input-panel bg-transparent p-0 border-0 border-none [border-color:currentcolor] rounded-none"><CashFlowEditor {controller} /><CalculationSettings {controller} /><div class="controls action-row flex items-center justify-between pt-6 [border-top-width:1px] [border-top-style:solid] [border-top-color:#e3e8e5] gap-3.5 [@media(width<=760px)]:items-stretch [@media(width<=760px)]:flex-col"><button type="button" disabled={!controller.valid || controller.status.kind === 'loading'} onclick={() => controller.calculate()}>Calculate with latest data</button></div><p class:success={controller.status.kind === 'success'} class:error={controller.status.kind === 'error'} class="status min-h-[1.4em] mt-3.5 mb-0 text-[#627269] text-[0.9rem] mx-0" aria-live="polite">{controller.status.message}</p>{#if controller.resultIsStale}<p class="stale-results mt-3 mb-0 [border-left-width:3px] [border-left-style:solid] [border-left-color:#b48432] bg-[#fff9e8] text-[#6b511b] text-[0.875rem] leading-[1.45] mx-0 px-3 py-2.5" role="status">Inputs have changed. The results below still reflect your last calculation. Calculate again to update them.</p>{/if}</div>{:else}<div id="historical-backtest-panel" role="tabpanel" aria-labelledby="historical-backtest-tab" class="panel input-panel bg-transparent p-0 border-0 border-none [border-color:currentcolor] rounded-none"><HistoricalSavingsSection controller={controller} active={setupTab === 'historical'} selectedScenario={historicalScenario} onResult={(display) => historicalDisplay = display} onSubmitReady={(submit) => historicalSubmit = submit} onLoadingChange={(loading) => historicalLoading = loading} onEndDateChangeReady={(setEndDate) => historicalSetEndDate = setEndDate} onEndDateChange={(value) => historicalEndDate = value} /><CalculationSettings controller={controller} historicalEndDate={historicalEndDate} onHistoricalEndDateChange={(value) => historicalSetEndDate?.(value)} /><div class="controls action-row flex items-center justify-between pt-6 [border-top-width:1px] [border-top-style:solid] [border-top-color:#e3e8e5] gap-3.5 [@media(width<=760px)]:items-stretch [@media(width<=760px)]:flex-col"><button type="button" disabled={historicalLoading} onclick={() => void historicalSubmit?.()}>{historicalLoading ? 'Calculating…' : 'Calculate historical savings'}</button></div></div>{/if}
      </section>
    </section>
    <section class="result-column min-w-0 bg-surface p-4 border border-solid border-line rounded-[5px]" aria-labelledby="result-workspace-heading"><div class="section-title result-column-title flex [align-items:end] justify-between pb-[11px] min-h-0 pt-0 mb-2.5 [border-bottom-width:1px] [border-bottom-style:solid] [border-bottom-color:var(--v2-border)] px-0 gap-5 [@media(width<=760px)]:items-start [@media(width<=760px)]:flex-col [@media(width<=760px)]:gap-3"><div><p class="eyebrow mb-1.5 text-muted text-[0.65rem] font-bold tracking-[0.09em] uppercase">04 · Analysis</p><h2 id="result-workspace-heading">Your comparison</h2></div></div>{#if setupTab === 'current'}<div class="result-tabs flex mt-0 mb-3.5 [border-bottom-width:1px] [border-bottom-style:solid] [border-bottom-color:var(--v2-border)] mx-0" role="tablist" aria-label="Analysis view"><button id="outcome-result-tab" type="button" role="tab" tabindex={resultTab === 'outcome' ? 0 : -1} aria-selected={resultTab === 'outcome'} aria-controls="outcome-result-panel" onclick={() => chooseResultTab('outcome')} onkeydown={handleResultTabKeydown}>Outcome</button><button id="future-result-tab" type="button" role="tab" tabindex={resultTab === 'future' ? 0 : -1} aria-selected={resultTab === 'future'} aria-controls="future-result-panel" onclick={() => chooseResultTab('future')} onkeydown={handleResultTabKeydown}>Future outlook</button></div>{#if resultTab === 'outcome'}<div id="outcome-result-panel" role="tabpanel" aria-labelledby="outcome-result-tab"><ResultsSection {controller} /></div>{:else}<div id="future-result-panel" role="tabpanel" aria-labelledby="future-result-tab"><FutureOutlookSection {controller} setupTab="current" onOpenMethodology={() => openMethodology()} /></div>{/if}{:else}<HistoricalSavingsResults display={historicalDisplay} selectedScenario={historicalScenario} onScenarioChange={(scenario) => historicalScenario = scenario} />{/if}</section>
  </div>
  <MethodologyDialog {controller} onOpenReady={(open) => openMethodology = open} />
  <aside class="notice mt-3.5 [border-left-width:3px] [border-left-style:solid] [border-left-color:#bd8a31] bg-[#fffdf6] text-[#555e55] text-[0.76rem] leading-[1.55] [border-top-color:var(--v2-border)] [border-right-color:var(--v2-border)] [border-bottom-color:var(--v2-border)] px-[13px] py-[11px]"><strong>Educational estimate, not tax advice.</strong> CSH2 prices are daily closes for Euronext Paris and may differ from your broker’s execution price. The backtest does not model spreads, variable commissions, fund-specific treatment, or other tax-law exceptions.</aside>
  <footer class="support flex flex-col items-center justify-center mt-4 gap-2.5"><p class="statbel-notice w-full mt-0 mb-5 text-[#617169] text-[0.78rem] leading-[1.5] text-center mx-0">Belgian CPI: <a href="https://bestat.statbel.fgov.be/bestat/api/views/86586e27-90ac-47c6-87ce-64b63194e605" target="_blank" rel="noopener noreferrer">Source Statbel</a> (Directorate-General Statistics – Statistics Belgium), <a href="https://statbel.fgov.be/en/cc-40" target="_blank" rel="license noopener noreferrer">CC BY 4.0</a>; adapted by selecting the all-items series, deduplicating, and normalizing monthly observations.</p><a href="https://www.buymeacoffee.com/plpeeters" target="_blank" rel="noopener noreferrer"><img src="https://cdn.buymeacoffee.com/buttons/v2/default-yellow.png" alt="Buy Me A Coffee" width="217" height="60" /></a><a class="github-button" href="https://github.com/PLPeeters/csh2-backtest" data-size="large" aria-label="View PLPeeters/csh2-backtest on GitHub">View on GitHub</a><p class="license-notice max-w-130 mt-1.5 mb-0 text-[#617169] text-[0.75rem] leading-[1.45] text-center mx-0"><a href="https://github.com/PLPeeters/csh2-backtest">CSH2 Backtest</a> by <a href="https://linkedin.com/in/plpeeters" target="_blank" rel="noopener noreferrer">Pierre-Louis Peeters</a> is licensed under <a href="https://creativecommons.org/licenses/by-nc/4.0/?ref=chooser-v1" target="_blank" rel="license noopener noreferrer">CC BY-NC 4.0</a></p><a class="license-icons flex items-center -mt-1 gap-[3px]" href="https://creativecommons.org/licenses/by-nc/4.0/?ref=chooser-v1" target="_blank" rel="noopener noreferrer" aria-label="CC BY-NC 4.0 licence"><img src="https://mirrors.creativecommons.org/presskit/icons/cc.svg?ref=chooser-v1" alt="Creative Commons" /><img src="https://mirrors.creativecommons.org/presskit/icons/by.svg" alt="Attribution" /><img src="https://mirrors.creativecommons.org/presskit/icons/nc.svg" alt="NonCommercial" /></a></footer>
</main>
