<script lang="ts">
  import type { Snippet } from 'svelte';
  import type { CalculationView } from '../types';
  import { date, duration, euro, number, percent } from '../services/formatters';
  import { cpiPointForDate } from '../../backtest.mjs';
  import LineChart from './LineChart.svelte';
  let { comparisonView, accountLabel = 'Account', portfolioChartLabel = 'your account', portfolioChartAriaLabel, timeWeightedChartLabel = 'your account', chartAccountLabel = 'Your account', initialReturnChartMode = 'time-weighted', beforeLedger }: { comparisonView?: CalculationView; accountLabel?: string; portfolioChartLabel?: string; portfolioChartAriaLabel?: string; timeWeightedChartLabel?: string; chartAccountLabel?: string; initialReturnChartMode?: 'portfolio-value' | 'time-weighted'; beforeLedger?: Snippet } = $props();
  const currentAccount = () => accountLabel === 'Account';
  const initialChartMode = () => initialReturnChartMode;
  let returnChartMode = $state<'portfolio-value' | 'time-weighted'>(initialChartMode());
  let view = $derived(comparisonView);
  let result = $derived(comparisonView?.result);
  let settings = $derived(comparisonView?.settings);
  let negative = $derived((result?.missedAmount ?? 0) < -0.005);
  let valuesAreEqual = $derived(Math.abs(result?.missedAmount ?? 0) < 0.005);
  // Keep displayed differences arithmetically consistent with the displayed
  // return values. Return values are stored in percentage points and
  // `percent()` shows two decimal places.
  const roundedReturn = (value: number) => Math.round(value * 100) / 100;
  let returnDifference = $derived(result?.csh2MoneyWeightedReturn !== undefined && result.accountMoneyWeightedReturn !== undefined ? roundedReturn(result.csh2MoneyWeightedReturn) - roundedReturn(result.accountMoneyWeightedReturn) : undefined);
  let returnDifferenceValueLabel = $derived(returnDifference === undefined ? undefined : Math.abs(returnDifference) < 0.005 ? '0' : `${returnDifference > 0 ? '+' : '−'}${percent(Math.abs(returnDifference))}`);
  let timeWeightedDifference = $derived(result?.csh2TimeWeightedReturn !== undefined && result.accountTimeWeightedReturn !== undefined ? roundedReturn(result.csh2TimeWeightedReturn) - roundedReturn(result.accountTimeWeightedReturn) : undefined);
  let timeWeightedDifferenceValueLabel = $derived(timeWeightedDifference === undefined ? undefined : Math.abs(timeWeightedDifference) < 0.005 ? '0' : `${timeWeightedDifference > 0 ? '+' : '−'}${percent(Math.abs(timeWeightedDifference))}`);
  let accountTerminalValue = $derived(result ? result.netLiquidationValue - result.missedAmount : 0);
  let valuationCpi = $derived(view ? cpiPointForDate(view.cpiMetadata.indices, view.to) : undefined);
  let portfolioProjection = $derived(view?.returnSeries.portfolioValue.projected);
  let timeWeightedProjection = $derived(view?.returnSeries.timeWeighted.projected);
  let projectedCrossover = $derived(result?.projectedCrossover);
  let portfolioChartTo = $derived(portfolioProjection?.throughDate ?? view?.to);
  let timeWeightedChartTo = $derived(timeWeightedProjection?.throughDate ?? view?.to);
</script>
<section class="comparison-results" aria-live="polite">
  {#if view && result && settings}
  <div class="result-heading"><div><p class="eyebrow">As of {result.valuation.date}</p><h2>Backtest result</h2></div></div>
  {#if settings.returnMode === 'real'}<p class="real-coverage-note">Inflation-adjusted returns use Belgian CPI.{#if valuationCpi?.status === 'extrapolated'}&nbsp;The latest portion is provisional and extrapolated from trailing 12-month observed inflation after {valuationCpi.lowerMonth}.{/if}</p>{/if}
  <div class="result-summary" aria-label="Terminal comparison summary">
    <article class:negative class:comparison-secondary={valuesAreEqual} class="metric main result-summary-card result-summary-outcome"><p>{valuesAreEqual ? `CSH2 and ${accountLabel.toLowerCase()} have the same value` : negative ? `CSH2 is behind ${currentAccount() ? 'your account balance' : accountLabel.toLowerCase()} by` : `CSH2 is ahead of ${currentAccount() ? 'your account balance' : accountLabel.toLowerCase()} by`}</p><strong>{result.missedAmount < 0 ? '−' : result.missedAmount > 0 ? '+' : ''}{euro.format(Math.abs(result.missedAmount))}</strong><small>{#if returnDifferenceValueLabel === undefined}—{:else}<b>{returnDifferenceValueLabel}</b> p.p. p.a. (MWR){/if}</small></article>
    <div class="result-summary-support" aria-label="Net value comparison">
      <article class="result-summary-support-item"><p>Net CSH2 value {currentAccount() ? 'if sold today' : 'at end date'}</p><strong>{euro.format(result.netLiquidationValue)}</strong><small>{#if result.csh2MoneyWeightedReturn === undefined}—{:else}<b>{percent(result.csh2MoneyWeightedReturn)}%</b> p.a. (MWR){/if}</small></article>
      <article class="result-summary-support-item"><p>{accountLabel} value {currentAccount() ? 'if sold today' : 'at end date'}</p><strong>{euro.format(accountTerminalValue)}</strong><small>{#if result.accountMoneyWeightedReturn === undefined}—{:else}<b>{percent(result.accountMoneyWeightedReturn)}%</b> p.a. (MWR){/if}</small></article>
    </div>
  </div>
  <section class="value-bridge" aria-labelledby="value-bridge-heading">
    <div class="value-bridge-heading"><p class="eyebrow">CSH2 value bridge</p><h3 id="value-bridge-heading">How the net value is formed</h3></div>
    <dl class="value-bridge-grid">
      <div><dt>Gross CSH2 value</dt><dd>{euro.format(result.grossValue)}</dd><small>{number.format(result.units)} units</small></div>
      <div><dt>Available cash</dt><dd>{euro.format(result.availableCash)}</dd><small>Uninvested after whole-share purchases</small></div>
      <div><dt>Exit costs</dt><dd>−{euro.format(result.terminalTob + result.terminalCgt + result.terminalReyndersTax + result.terminalBrokerFee)}</dd><small>Taxes {euro.format(result.terminalTob + result.terminalCgt + result.terminalReyndersTax)} · fees {euro.format(result.terminalBrokerFee)}</small></div>
      <div class="value-bridge-total"><dt>Net value {currentAccount() ? 'if sold today' : 'at end date'}</dt><dd>{euro.format(result.netLiquidationValue)}</dd></div>
    </dl>
    <p class="value-bridge-paid">Already incurred: {euro.format(result.paidTob + result.paidCgt + result.paidReyndersTax + result.paidBrokerFees)} <span>({euro.format(result.paidTob + result.paidCgt + result.paidReyndersTax)} taxes · {euro.format(result.paidBrokerFees)} broker fees)</span></p>
  </section>
  <section class="panel" aria-labelledby="return-heading">
    <div class="section-title"><div><p class="eyebrow">Historical performance</p><h3 id="return-heading">{returnChartMode === 'portfolio-value' ? 'Euro portfolio value over time' : 'Cash-flow-neutral performance'}</h3></div><div class="return-mode-picker" role="group" aria-label="Performance chart view"><button type="button" aria-pressed={returnChartMode === 'portfolio-value'} onclick={() => returnChartMode = 'portfolio-value'}>Portfolio value</button><button type="button" aria-pressed={returnChartMode === 'time-weighted'} onclick={() => returnChartMode = 'time-weighted'}>Performance</button></div></div>
    <p class="chart-key"><span class="chart-key-csh2">CSH2 backtest</span>{#if (returnChartMode === 'portfolio-value' ? view.returnSeries.portfolioValue.overnight.length : view.returnSeries.timeWeighted.overnight.length)}<span class="chart-key-estr">Gross €STR</span>{/if}<span class="chart-key-account">{accountLabel === 'Account' ? 'Your account' : accountLabel}</span>{#if (returnChartMode === 'portfolio-value' && portfolioProjection) || (returnChartMode === 'time-weighted' && timeWeightedProjection)}<span class="chart-key-projected">Projection</span>{/if}</p>
    {#if returnChartMode === 'portfolio-value'}
      <p class="chart-explanation">{currentAccount() ? 'Actual CSH2 net liquidation value and account balance after the same deposits and withdrawals. Values are shown in current euros and are not investment returns.' : 'Actual CSH2 net liquidation value and historical savings value after the same deposits. Values are shown in current euros and are not investment returns.'}</p>
      {#if portfolioProjection}<p class="chart-explanation projection-explanation">Dashed through {date.format(new Date(`${portfolioProjection.throughDate}T00:00:00Z`))}: {currentAccount() ? `assumes no further cash flows, the selected CSH2 rate scenario of ${percent(portfolioProjection.csh2AnnualRatePercent)}%, and each entered fidelity premium is paid on its earned date.` : `continues the entered deposit schedule and historical savings rates, while holding the selected CSH2 rate scenario of ${percent(portfolioProjection.csh2AnnualRatePercent)}% and the latest €STR rate constant. Acquired fidelity premiums are included from their acquisition date; once credited, they join principal and can accrue normally.`}{#if portfolioProjection.baseAnnualRatePercent !== undefined} The full account balance compounds at the entered {percent(portfolioProjection.baseAnnualRatePercent)}% annual base rate, and each paid premium joins that balance for subsequent accrual.{/if}</p>{/if}
      {#if view.returnSeries.portfolioValue.csh2.length || view.returnSeries.portfolioValue.account.length}<LineChart accountLabel={chartAccountLabel} crossoverDate={projectedCrossover?.date} data={view.returnSeries.portfolioValue} unit="euro" from={view.from} to={portfolioChartTo} ariaLabel={portfolioChartAriaLabel ?? `Portfolio value in euro for CSH2 and ${portfolioChartLabel} using the same external cash flows`} />{:else}<p class="chart-empty">There isn’t enough history yet to plot portfolio values.</p>{/if}
    {:else}
      <p class="chart-explanation">{currentAccount() ? 'Geometric linking removes the deposits and withdrawals themselves from performance. CSH2 still includes the broker fees, transaction taxes, and selected gain taxes those trades trigger; the account includes entered credited and accrued interest; €STR is a gross, untaxed market benchmark.' : 'Geometric linking removes the external deposits from performance. CSH2 includes the broker fees, transaction taxes, and selected gain taxes those trades trigger; historical savings includes base interest and fidelity premiums; €STR is a gross, untaxed market benchmark.'}{#if settings.returnMode === 'real'} The chart begins only once both CPI endpoints are available.{/if}</p>
      {#if timeWeightedProjection}<p class="chart-explanation projection-explanation">Dashed through {date.format(new Date(`${timeWeightedProjection.throughDate}T00:00:00Z`))}: {currentAccount() ? `extends each observed TWR endpoint with no further cash flows, the selected CSH2 rate scenario of ${percent(timeWeightedProjection.csh2AnnualRatePercent)}%, the latest €STR rate of ${percent(timeWeightedProjection.overnightRatePercent)}%, and ${timeWeightedProjection.baseAnnualRatePercent !== undefined ? `the entered account base rate of ${percent(timeWeightedProjection.baseAnnualRatePercent)}%` : 'the account’s observed interest assumptions'}; future fidelity premiums are credited on their earned dates and included as internal account returns.` : `continues the entered deposit schedule and historical savings rates, with the selected CSH2 and latest €STR rates held constant. Acquired fidelity premiums are included from acquisition until credited on the next quarterly payout date, then join principal and can accrue normally.`}{#if settings.returnMode === 'real'} This forward section is provisional and inflation-adjusted using trailing 12-month observed CPI extrapolation.{/if}</p>{/if}
      {#if view.returnSeries.timeWeighted.csh2.length || view.returnSeries.timeWeighted.overnight.length || view.returnSeries.timeWeighted.account.length}<LineChart accountLabel={chartAccountLabel} crossoverDate={undefined} data={view.returnSeries.timeWeighted} cpiIndices={settings.returnMode === 'real' ? view.cpiMetadata.indices : undefined} from={view.from} to={timeWeightedChartTo} ariaLabel={`Time-weighted performance of CSH2, gross Euro overnight rates, and ${timeWeightedChartLabel}, excluding external cash flows`} />{:else}<p class="chart-empty">There isn’t enough CPI-covered history yet to plot time-weighted performance.</p>{/if}
    {/if}
  </section>
  <details class="performance-details">
    <summary>Costs and calculation details</summary>
    <div class="performance-details-content">
      <section class="details-section returns-details" aria-labelledby="returns-details-heading"><h3 id="returns-details-heading">Returns</h3><div class="table-wrap"><table class="comparison-details-table"><thead><tr><th>Measure</th><th>CSH2</th><th>{accountLabel}</th><th>Difference</th></tr></thead><tbody><tr><th scope="row">Annualized outcome (MWR)</th><td>{result.csh2MoneyWeightedReturn === undefined ? '—' : `${percent(result.csh2MoneyWeightedReturn)}%`}</td><td>{result.accountMoneyWeightedReturn === undefined ? '—' : `${percent(result.accountMoneyWeightedReturn)}%`}</td><td>{returnDifferenceValueLabel === undefined ? '—' : `${returnDifferenceValueLabel} p.p.`}</td></tr><tr><th scope="row">Investment performance (TWR)</th><td>{result.csh2TimeWeightedReturn === undefined ? '—' : `${percent(result.csh2TimeWeightedReturn)}%`}</td><td>{result.accountTimeWeightedReturn === undefined ? '—' : `${percent(result.accountTimeWeightedReturn)}%`}</td><td>{timeWeightedDifferenceValueLabel === undefined ? '—' : `${timeWeightedDifferenceValueLabel} p.p.`}</td></tr></tbody></table></div><p class="details-note"><b>MWR</b> includes the timing of external cash flows. <b>TWR</b> removes those cash flows to show investment performance. Both retain the applicable costs and tax treatment.</p></section>
    {#if result.observedHoldingPeriods}<section class="details-section observed-milestones" aria-labelledby="observed-milestones-heading"><h3 id="observed-milestones-heading">Observed backtest milestones</h3><div class="metric-row metric-row-values"><article class="metric"><p>CSH2 backtest first broke even after</p><strong>{result.observedHoldingPeriods.breakEven && result.observedHoldingPeriods.from ? duration(result.observedHoldingPeriods.from, result.observedHoldingPeriods.breakEven.date) : 'Not yet'}</strong><small>{result.observedHoldingPeriods.breakEven ? `First observed on ${date.format(new Date(`${result.observedHoldingPeriods.breakEven.date}T00:00:00Z`))}.` : result.observedHoldingPeriods.from ? 'The CSH2 backtest has not broken even yet.' : 'No CSH2 purchase was executed.'} Net CSH2 liquidation value versus external capital, excluding account interest; includes transaction costs and selected taxes.</small></article><article class="metric"><p>CSH2 backtest first matched €STR after</p><strong>{result.observedHoldingPeriods.matchOvernight && result.observedHoldingPeriods.from ? duration(result.observedHoldingPeriods.from, result.observedHoldingPeriods.matchOvernight.date) : 'Not yet'}</strong><small>{result.observedHoldingPeriods.matchOvernight ? `First observed on ${date.format(new Date(`${result.observedHoldingPeriods.matchOvernight.date}T00:00:00Z`))}.` : result.observedHoldingPeriods.from ? 'The CSH2 backtest has not matched €STR yet.' : 'No CSH2 purchase was executed.'} Compares the same external cash flows, excluding account interest.</small></article></div></section>{/if}
    <section class="details-section cost-details" aria-labelledby="cost-details-heading"><h3 id="cost-details-heading">Costs</h3><div class="table-wrap"><table class="comparison-details-table"><thead><tr><th>Cost</th><th>Already paid</th><th>{currentAccount() ? 'On sale today' : 'At end date'}</th><th>Total</th></tr></thead><tbody><tr><th scope="row">Taxes</th><td>{euro.format(result.paidTob + result.paidCgt + result.paidReyndersTax)}</td><td>{euro.format(result.terminalTob + result.terminalCgt + result.terminalReyndersTax)}</td><td>{euro.format(result.paidTob + result.paidCgt + result.paidReyndersTax + result.terminalTob + result.terminalCgt + result.terminalReyndersTax)}</td></tr><tr><th scope="row">Broker fees</th><td>{euro.format(result.paidBrokerFees)}</td><td>{euro.format(result.terminalBrokerFee)}</td><td>{euro.format(result.paidBrokerFees + result.terminalBrokerFee)}</td></tr><tr class="comparison-details-total"><th scope="row">Total costs</th><td>{euro.format(result.paidTob + result.paidCgt + result.paidReyndersTax + result.paidBrokerFees)}</td><td>{euro.format(result.terminalTob + result.terminalCgt + result.terminalReyndersTax + result.terminalBrokerFee)}</td><td>{euro.format(result.paidTob + result.paidCgt + result.paidReyndersTax + result.paidBrokerFees + result.terminalTob + result.terminalCgt + result.terminalReyndersTax + result.terminalBrokerFee)}</td></tr></tbody></table></div><p class="details-note">Taxes already paid: TOB {euro.format(result.paidTob)} · {settings.applyReyndersTax ? `Reynders Tax ${euro.format(result.paidReyndersTax)}` : `CGT ${euro.format(result.paidCgt)}`}. Exit costs are deducted from the gross CSH2 value and available cash in the value bridge above.</p></section>
    <section class="details-section position-details" aria-labelledby="position-details-heading"><h3 id="position-details-heading">Position</h3><p class="position-line"><b>{number.format(result.units)} CSH2 units</b> · {euro.format(result.grossValue)} gross value · {euro.format(result.availableCash)} available cash · {euro.format(result.netLiquidationValue)} net liquidation value</p></section>
      {@render beforeLedger?.()}
    </div>
  </details>
  <details class="ledger-disclosure">
    <summary>Transaction ledger</summary>
  <section class="panel ledger"><h3 class="sr-only">Transaction ledger</h3><div class="table-wrap"><table><thead><tr><th>Date</th><th>Type</th><th>Amount</th><th>Price used</th><th>Units</th><th>Cash remaining</th><th>Broker fee</th><th>TOB</th>{#if !settings.applyReyndersTax}<th>CGT</th>{/if}{#if settings.applyReyndersTax}<th>Reynders Tax</th>{/if}{#if settings.applyCapitalGainsExemption && !settings.applyReyndersTax}<th>Exonerated CGT</th>{/if}</tr></thead><tbody>{#each result.entries as entry}<tr><td>{entry.date}</td><td>{entry.interestPayment ? 'Interest payment' : entry.type === 'inflow' ? 'Inflow / buy' : 'Outflow / sell'}</td><td>{euro.format(entry.amount)}</td><td>{entry.price === undefined ? '—' : euro.format(entry.price)}{entry.priceKind && entry.priceKind !== 'close' ? ` (${entry.priceKind})` : ''}</td><td>{entry.interestPayment ? '—' : number.format(entry.units)}</td><td>{euro.format(entry.remainingCash)}</td><td>{euro.format(entry.brokerFee)}</td><td>{euro.format(entry.tob)}</td>{#if !settings.applyReyndersTax}<td>{entry.cgt ? euro.format(entry.cgt) : '—'}</td>{/if}{#if settings.applyReyndersTax}<td>{entry.reyndersTax ? euro.format(entry.reyndersTax) : '—'}</td>{/if}{#if settings.applyCapitalGainsExemption && !settings.applyReyndersTax}<td>{entry.exoneratedCgt ? euro.format(entry.exoneratedCgt) : '—'}</td>{/if}</tr>{/each}</tbody></table></div></section>
  </details>
  <details class="methodology-disclosure">
    <summary>Methodology and assumptions</summary>
    <div class="methodology-disclosure-content">
      <p>FIFO lots are used for CSH2 trades. Broker fees, transaction taxes, and the selected gain-tax treatment are applied to the simulated transactions.</p>
      <p>By default, positive realised gains from 2026 onward use 10% CGT. For purchases before 2026, the tax basis is the higher of the original price and the 31 December 2025 CSH2 close.</p>
      <p>Values are educational estimates, not tax advice. CSH2 prices are daily closes and may differ from broker execution prices.</p>
    </div>
  </details>
  {/if}
</section>
