<script lang="ts">
  import type { BacktestController } from '../state/backtest.svelte';
  import { date, duration, euro, number, percent, relativeUpdatedAt, updatedAt } from '../services/formatters';
  import LineChart from './LineChart.svelte';
  let { controller }: { controller: BacktestController } = $props();
</script>
<section id="results" aria-live="polite">
{#if controller.view}
  {@const result = controller.view.result}
  {@const settings = controller.view.settings}
  {@const negative = result.missedAmount < 0}
  {@const csh2UpdatedAt = new Date(controller.view.metadata.cachedAt)}
  {@const estrUpdatedAt = controller.view.rateMetadata.cachedAt ? new Date(controller.view.rateMetadata.cachedAt) : undefined}
    <div class="result-heading"><div><p class="eyebrow">As of {result.valuation.date}</p><h2>Backtest result</h2></div><p class="source"><span class="timestamp-wrapper"><button type="button" class="timestamp" aria-describedby="csh2-update-tooltip">CSH2 data last updated {relativeUpdatedAt(csh2UpdatedAt)}</button><span id="csh2-update-tooltip" class="timestamp-tooltip" role="tooltip">{updatedAt.format(csh2UpdatedAt)}</span></span><br />{#if estrUpdatedAt}<span class="timestamp-wrapper"><button type="button" class="timestamp" aria-describedby="estr-update-tooltip">€STR data last updated {relativeUpdatedAt(estrUpdatedAt)}</button><span id="estr-update-tooltip" class="timestamp-tooltip" role="tooltip">{updatedAt.format(estrUpdatedAt)}</span></span>{:else}<span>€STR data last updated unavailable</span>{/if}</p></div>
    <div class="metrics">
      <article class:negative class="metric main missed-result"><p>{negative ? 'CSH2 would currently be below your account balance by' : 'You missed out on'}</p><strong>{euro.format(Math.abs(result.missedAmount))}</strong><small>{result.missedSharePercent === undefined ? 'Your account balance is zero.' : negative ? `a shortfall equal to ${percent(Math.abs(result.missedSharePercent))}% of your account balance, including interest` : `which is ${percent(result.missedSharePercent)}% of your account balance, including interest`}</small>
        {#if negative && result.breakEvenEstimate}<small>Estimated catch-up with your account in <b>{duration(result.valuation.date, result.breakEvenEstimate.date)}</b></small><small>(using the selected CSH2 rate scenario of {percent(result.breakEvenEstimate.csh2AnnualRatePercent)}%)</small>{:else if negative}<small>Catch-up with your account can’t be estimated from the selected CSH2 rate scenario.</small>{/if}
      </article>
      <div class="metric-row metric-row-values"><article class="metric"><p>CSH2 backtest first broke even after</p><strong>{result.observedHoldingPeriods.breakEven && result.observedHoldingPeriods.from ? duration(result.observedHoldingPeriods.from, result.observedHoldingPeriods.breakEven.date) : 'Not yet'}</strong><small>{result.observedHoldingPeriods.breakEven ? `First observed on ${date.format(new Date(`${result.observedHoldingPeriods.breakEven.date}T00:00:00Z`))}.` : result.observedHoldingPeriods.from ? 'The CSH2 backtest has not broken even yet.' : 'No CSH2 purchase was executed.'} Net CSH2 liquidation value versus external capital, excluding account interest; includes transaction costs and selected taxes.</small></article><article class="metric"><p>CSH2 backtest first matched €STR after</p><strong>{result.observedHoldingPeriods.matchOvernight && result.observedHoldingPeriods.from ? duration(result.observedHoldingPeriods.from, result.observedHoldingPeriods.matchOvernight.date) : 'Not yet'}</strong><small>{result.observedHoldingPeriods.matchOvernight ? `First observed on ${date.format(new Date(`${result.observedHoldingPeriods.matchOvernight.date}T00:00:00Z`))}.` : result.observedHoldingPeriods.from ? 'The CSH2 backtest has not matched €STR yet.' : 'No CSH2 purchase was executed.'} Compares the same external cash flows, excluding account interest.</small></article></div>
      <div class="metric-row metric-row-values"><article class="metric"><p>Net value if sold today</p><strong>{euro.format(result.netLiquidationValue)}</strong><small>After estimated final TOB and applicable tax</small></article><article class="metric"><p>Gross CSH2 value</p><strong>{euro.format(result.grossValue)}</strong><small>{number.format(result.units)} CSH2 units{result.availableCash ? ` · ${euro.format(result.availableCash)} cash` : ''}</small></article></div>
      <div class="metric-row metric-row-details"><article class="metric"><p>Taxes already paid</p><strong>{euro.format(result.paidTob + result.paidCgt + result.paidReyndersTax)}</strong><small>TOB {euro.format(result.paidTob)} · {settings.applyReyndersTax ? `Reynders Tax ${euro.format(result.paidReyndersTax)}` : `CGT ${euro.format(result.paidCgt)}`}</small></article><article class="metric"><p>Taxes if sold today</p><strong>{euro.format(result.terminalTob + result.terminalCgt + result.terminalReyndersTax)}</strong><small>TOB {euro.format(result.terminalTob)} · {settings.applyReyndersTax ? `Reynders Tax ${euro.format(result.terminalReyndersTax)}` : `CGT ${euro.format(result.terminalCgt)}`}</small></article><article class="metric"><p>Broker fees</p><strong>{euro.format(result.paidBrokerFees + result.terminalBrokerFee)}</strong><small>Paid {euro.format(result.paidBrokerFees)} · if sold today {euro.format(result.terminalBrokerFee)}</small></article></div>
      {#if result.fidelityPremiumAssessments.length}
        <section class="metric fidelity-assessments" aria-labelledby="fidelity-timing-heading"><div class="section-title fidelity-assessments-heading"><div><p class="eyebrow">Savings account comparison</p><h3 id="fidelity-timing-heading">Fidelity premium timing</h3></div></div><div class="table-wrap"><table class="fidelity-timing-table"><thead><tr><th>Base amount</th><th>Earned</th><th>Payout</th><th>Current period</th><th>Next full year</th><th>Recommendation</th></tr></thead><tbody>
          {#each result.fidelityPremiumAssessments as assessment (assessment.id)}
            <tr><td><span class="fidelity-mobile-label" aria-hidden="true">Base amount</span>{euro.format(assessment.baseAmount)}</td><td><span class="fidelity-mobile-label" aria-hidden="true">Earned</span>{date.format(new Date(`${assessment.earnedDate}T00:00:00Z`))}</td><td><span class="fidelity-mobile-label" aria-hidden="true">Payout</span>{euro.format(assessment.finalPayoutAmount)}</td><td class:comparison-winner={assessment.currentPeriodPreferred !== 'either'}><span class="fidelity-mobile-label" aria-hidden="true">Current period</span>{assessment.currentPeriodPreferred === 'move now' ? `CSH2 +${euro.format(Math.abs(assessment.currentPeriodDifference))}` : assessment.currentPeriodPreferred === 'wait' ? `Account +${euro.format(Math.abs(assessment.currentPeriodDifference))}` : 'Effectively equal'}</td><td class:comparison-winner={assessment.nextYearCsh2Value !== undefined && assessment.nextYearAccountValue !== undefined}><span class="fidelity-mobile-label" aria-hidden="true">Next full year</span>{assessment.nextYearCsh2Value !== undefined && assessment.nextYearAccountValue !== undefined ? assessment.nextYearCsh2Value > assessment.nextYearAccountValue ? `CSH2 +${euro.format(assessment.nextYearCsh2Value - assessment.nextYearAccountValue)}` : `Account +${euro.format(assessment.nextYearAccountValue - assessment.nextYearCsh2Value)}` : assessment.currentPeriodPreferred === 'wait' ? 'Enter account rates' : '—'}</td><td class="timing-recommendation"><span class="fidelity-mobile-label" aria-hidden="true">Recommendation</span>{assessment.recommendation === 'move now' ? 'Transfer now' : assessment.recommendation === 'move after payout' ? `Transfer ${date.format(new Date(`${assessment.transferDate}T00:00:00Z`))}` : assessment.recommendation === 'keep in account' ? 'Keep for next year' : assessment.recommendation === 'wait, then reassess' ? `Reassess ${date.format(new Date(`${assessment.transferDate}T00:00:00Z`))}` : 'Either'}</td></tr>
          {/each}
        </tbody></table></div><small class="timing-notes"><span>Ordered by the recommended transfer or reassessment date, with keep decisions last. Each row is one cash-transfer recommendation; legal tranche allocation is handled internally.</span><span><b>Current period</b> compares moving now with waiting for base-rate accrual until the entered payout.<br><b>Next full year</b> compares CSH2 with the entered base rate plus fidelity premium.</span><span>Withdrawal priority is recalculated after each premium is acquired. Timing calculations use fractional shares, and amounts transferred on the same date are combined into one CSH2 purchase.</span><span>Uses the selected CSH2 rate scenario of {percent(result.fidelityPremiumAssessments[0].csh2AnnualRatePercent)}% and the selected transaction and tax settings.</span></small></section>
      {/if}
    </div>
    <section class="panel chart-panel" aria-labelledby="return-heading"><div class="section-title"><div><p class="eyebrow">After transaction costs and applicable tax</p><h3 id="return-heading">Cumulative backtest return</h3></div></div><p class="chart-key"><span class="chart-key-csh2">CSH2 backtest</span><span class="chart-key-estr">Euro overnight benchmark portfolio</span><span class="chart-key-account">Your account</span>{#if controller.view.returnSeries.projected}<span class="chart-key-projected">Projection</span>{/if}</p>{#if controller.view.returnSeries.projected}{@const projection = controller.view.returnSeries.projected}<p class="chart-explanation projection-explanation">Dashed through {date.format(new Date(`${projection.throughDate}T00:00:00Z`))}: assumes no further cash flows, the selected CSH2 rate scenario of {percent(projection.csh2AnnualRatePercent)}%, the overnight rate remains {percent(projection.overnightRatePercent)}%, and each entered fidelity premium is paid on its earned date.{#if projection.baseAnnualRatePercent !== undefined} The full account balance compounds at the entered {percent(projection.baseAnnualRatePercent)}% annual base rate, and each paid premium joins that balance for subsequent accrual.{/if}</p>{/if}{#if controller.view.returnSeries.csh2.length || controller.view.returnSeries.overnight.length || controller.view.returnSeries.account.length}<LineChart data={controller.view.returnSeries} ariaLabel="Cumulative return of your account compared with CSH2 and a euro overnight benchmark portfolio using the same external cash flows" />{:else}<p class="chart-empty">There isn’t enough history yet to plot the cumulative backtest return.</p>{/if}</section>
{/if}
{#if controller.view}
    {@const result = controller.view.result}
    {@const settings = controller.view.settings}
    <section class="panel ledger"><h3>Transaction ledger</h3><div class="table-wrap"><table><thead><tr><th>Date</th><th>Type</th><th>Amount</th><th>Price used</th><th>Units</th><th>Cash remaining</th><th>Broker fee</th><th>TOB</th>{#if !settings.applyReyndersTax}<th>CGT</th>{/if}{#if settings.applyReyndersTax}<th>Reynders Tax</th>{/if}{#if settings.applyCapitalGainsExemption && !settings.applyReyndersTax}<th>Exonerated CGT</th>{/if}</tr></thead><tbody>{#each result.entries as entry}<tr><td>{entry.date}</td><td>{entry.interestPayment ? 'Interest payment' : entry.type === 'inflow' ? 'Inflow / buy' : 'Outflow / sell'}</td><td>{euro.format(entry.amount)}</td><td>{entry.price === undefined ? '—' : euro.format(entry.price)}{entry.priceKind && entry.priceKind !== 'close' ? ` (${entry.priceKind})` : ''}</td><td>{entry.interestPayment ? '—' : number.format(entry.units)}</td><td>{euro.format(entry.remainingCash)}</td><td>{euro.format(entry.brokerFee)}</td><td>{euro.format(entry.tob)}</td>{#if !settings.applyReyndersTax}<td>{entry.cgt ? euro.format(entry.cgt) : '—'}</td>{/if}{#if settings.applyReyndersTax}<td>{entry.reyndersTax ? euro.format(entry.reyndersTax) : '—'}</td>{/if}{#if settings.applyCapitalGainsExemption && !settings.applyReyndersTax}<td>{entry.exoneratedCgt ? euro.format(entry.exoneratedCgt) : '—'}</td>{/if}</tr>{/each}</tbody></table></div></section>
{/if}
</section>
